# Generated by the synkro-rs release pipeline (SYN-481) — do not edit by hand.
# `scripts/homebrew-formula.py` regenerates this from a tagged release's tarballs
# and the public tap-mirror URLs on every release. To change the formula, change
# the generator, not this file.

class Synkro < Formula
  desc "Local policy enforcement engine for AI coding agents"
  homepage "https://github.com/synkro-sh/synkro-rs"
  version "0.2.0-rc.15"

  # Hosted mode is the default. Local services are installed separately only
  # when the user explicitly chooses local mode.

  # macOS ships Apple Silicon only (Intel macOS was dropped). The url lives
  # directly under on_macos — not nested in on_arm — so Homebrew never sees an
  # Intel-macOS branch with no url (which newer Homebrew rejects at tap time);
  # `depends_on arch: :arm64` refuses the install on an Intel Mac with a clear
  # message instead.
  on_macos do
    depends_on arch: :arm64
    url "https://github.com/synkro-sh/homebrew-tap/releases/download/v0.2.0-rc.15/synkro-aarch64-apple-darwin.tar.gz"
    sha256 "0f26a74f1dfb0433b5eee8dc03be4a27edf5f608f127ec431875efa99b89fd86"
  end

  on_linux do
    on_arm do
      url "https://github.com/synkro-sh/homebrew-tap/releases/download/v0.2.0-rc.15/synkro-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "a489c8e818dfb3beaa9218d1d1970a3ac67b8434c9dc15554799b3aa239ad356"
    end
    on_intel do
      url "https://github.com/synkro-sh/homebrew-tap/releases/download/v0.2.0-rc.15/synkro-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "7bf2f7dfbe69e5e5b90316625b087b86e46eb35ef97e797e1c1c352202429cc5"
    end
  end

  def install
    bin.install "synkro"
  end

  test do
    assert_match "synkro", shell_output("#{bin}/synkro --version")
  end
end
