# Generated by the synkro-rs release pipeline (SYN-481) — do not edit by hand.
# `scripts/homebrew-formula.py` regenerates this from a tagged release's tarballs
# and the public tap-mirror URLs on every release. To change the formula, change
# the generator, not this file.

class Synkro < Formula
  desc "Local policy enforcement engine for AI coding agents"
  homepage "https://github.com/synkro-sh/synkro-rs"
  version "0.2.0-rc.14"

  # Hosted mode is the default. Local services are installed separately only
  # when the user explicitly chooses local mode.

  # macOS ships Apple Silicon only (Intel macOS was dropped). The url lives
  # directly under on_macos — not nested in on_arm — so Homebrew never sees an
  # Intel-macOS branch with no url (which newer Homebrew rejects at tap time);
  # `depends_on arch: :arm64` refuses the install on an Intel Mac with a clear
  # message instead.
  on_macos do
    depends_on arch: :arm64
    url "https://github.com/synkro-sh/homebrew-tap/releases/download/v0.2.0-rc.14/synkro-aarch64-apple-darwin.tar.gz"
    sha256 "d7f91ba62f9fcdd06aea71f63a87d3ca5122c9adada9cffa59b0c73fdfabab99"
  end

  on_linux do
    on_arm do
      url "https://github.com/synkro-sh/homebrew-tap/releases/download/v0.2.0-rc.14/synkro-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "3f3bf9a4238f11aeb378557c525a4f4d5ac8cc28867295f4b643de2088d0de02"
    end
    on_intel do
      url "https://github.com/synkro-sh/homebrew-tap/releases/download/v0.2.0-rc.14/synkro-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "d6b11607da7e8283a3ec73139829e548a58958bbdfb27139a60368f879ad07c9"
    end
  end

  def install
    bin.install "synkro"
  end

  test do
    assert_match "synkro", shell_output("#{bin}/synkro --version")
  end
end
