# Generated by the release workflow in synkro-sh/synkro-rs.
# Do not edit by hand: the next release overwrites this file.

class Synkro < Formula
  desc "Local policy enforcement engine for AI coding agents"
  homepage "https://github.com/synkro-sh/synkro-rs"
  version "0.1.4"

  depends_on "restatedev/tap/restate-server"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/synkro-sh/homebrew-tap/releases/download/v0.1.4/synkro-aarch64-apple-darwin.tar.gz"
      sha256 "e003307154480231be990a3907730c3e12f7796bd9b46e3581ca886f4019d068"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/synkro-sh/homebrew-tap/releases/download/v0.1.4/synkro-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "4c838f38b45e86dcb1088e19ca46b76e06cbb64d4fd66050fb7037807a60ab84"
    end
    on_intel do
      url "https://github.com/synkro-sh/homebrew-tap/releases/download/v0.1.4/synkro-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "afd6afb1523d822de3c26111f2bd24928973b97fa3f0e36ca89bb6460c876853"
    end
  end

  def install
    bin.install "synkro"
  end

  test do
    assert_match "synkro", shell_output("#{bin}/synkro --version")
  end
end
